### PR TITLE
Delete 2013-01-15-The-Blues-in-D-for-Aaron-Swartz.md

### PR DESCRIPTION
**Pull request by pgayed**
Hi. I'm the author of this post. Please delete it when you can. With thanks, Peter

### CODE REVIEW

**Comment by pgayed** [comment]
Author of the post, here. Just requesting to remove my post. Thanks for your time. Wishing all Swartz family & friends all the best.

**Comment by pgayed** [comment]
thanks derek -- much appreciated.

**Comment by pgayed** [comment]
Sorry -- could someone explain when my post will be deleted? I see that @hammerdr merged my commit but it seems as if the post is still live at rememberaaronsw.com/memories/The-Blues-in-D-for-Aaron-Swartz.html -- apologies in advance, I'm still new to GitHub.

**Comment by pgayed** [comment]
@hammerdr -- Hey Derek. Can you explain to me why my post if still live on the site?

**Comment by hammerdr** [comment]
The automated deployment mechanism doesn't function anymore. @bguthrie is the person that manages the S3 account where the site is hosted. Maybe he can manually delete the post?

**Pull request merged**
